import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { ArrowUpRightIcon, HouseIcon } from "@phosphor-icons/react/ssr";
import "./globals.css";
import { ROUTES } from "@/shared/config/routes";
import { cn } from "@/shared/lib/utils";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ru"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col font-sans">
        <nav
          aria-label="Основная навигация"
          className="absolute top-4 left-4 z-10"
        >
          <Link
            href={ROUTES.HOME}
            className="group inline-flex items-center gap-3 bg-card p-1 pr-3 text-xs font-medium text-card-foreground shadow-sm ring-1 ring-foreground/10 transition duration-200 outline-none hover:shadow-lg hover:ring-foreground/20 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-4 motion-safe:hover:-translate-y-1"
          >
            <span className="flex size-6 items-center justify-center bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
              <HouseIcon size={18} weight="duotone" aria-hidden="true" />
            </span>
            <span>На главную</span>
            <ArrowUpRightIcon
              size={16}
              aria-hidden="true"
              className="text-muted-foreground transition-transform group-hover:text-foreground motion-safe:group-hover:translate-x-0.5 motion-safe:group-hover:-translate-y-0.5"
            />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
